fix build
Error: Cannot find module 'fs/promises'
Require stack:
- C:\Users\Joker\github\GitHub-Dark-Upstream\tools\clean.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Joker\github\GitHub-Dark-Upstream\tools\clean.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
make: *** [Makefile:6: build] Error 1

~/github/GitHub-Dark-Upstream (master) $ make deps
make: Nothing to be done for 'deps'.

~/github/GitHub-Dark-Upstream (master) $ make deps

~/github/GitHub-Dark-Upstream (master) $ make
node tools/clean.js
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'fs/promises'
Require stack:
- C:\Users\Joker\github\GitHub-Dark-Upstream\tools\clean.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Joker\github\GitHub-Dark-Upstream\tools\clean.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
make: *** [Makefile:6: build] Error 1

~/github/GitHub-Dark-Upstream (master) $ make
node tools/clean.js
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'const fs = require('fs').promises;'
Require stack:
- C:\Users\Joker\github\GitHub-Dark-Upstream\tools\clean.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Joker\github\GitHub-Dark-Upstream\tools\clean.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
make: *** [Makefile:6: build] Error 1